name: PG Replication

on:
  push:
    branches: [ "main" ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 195.158.4.181
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.KEY }}
          # port: ${{ secrets.PORT }}
          script: |
            cd /var/www/server
            git pull